
DROP TABLE Photographer CASCADE;
DROP TABLE Client CASCADE;
DROP TABLE Job CASCADE;
DROP TABLE Photo CASCADE;

DROP TABLE JobType CASCADE;

DROP TABLE Package CASCADE;
DROP TABLE PhotoType CASCADE;
DROP TABLE PhotoInPackage CASCADE;

DROP TABLE Payment CASCADE;
/*DROP TABLE Credit CASCADE;*/

DROP TYPE jobmode;
